### ISSUE TITLE
Error in SecretBallot Tutorial

### ISSUE THREAD

**Issue by aleph2012** [oasislabs/devnet-issues#2]
# Bug report

**What is the current behavior?**
truffle compile
truffle migrate --network oasis
both ran successfully.

Getting an error running:
truffle test --network oasis

Here is the output:

Building contracts for Oasis
   Compiling Migrations.sol...
🔒 Compiling confidential_SecretBallot.sol as confidential...
TypeError: Cannot call a class as a function
    at _classCallCheck (/project/node_modules/@babel/runtime/helpers/classCallCheck.js:3:11)
    at module.exports.Web3 (/project/node_modules/web3/dist/web3.cjs.js:29:5)
    at new module.exports (/project/node_modules/web3c/index.node.js:12:8)
    at contract (/project/test/test_secret_ballot.js:10:17)
    at Suite.template (/truffle/packages/truffle/build/webpack:/packages/truffle-core/lib/test.js:220:1)
    at Suite.<anonymous> (/truffle/packages/truffle/build/webpack:/packages/truffle-core/lib/test.js:224:57)
    at Object.create (/truffle/packages/truffle/node_modules/mocha/lib/interfaces/common.js:112:19)
    at Function.context.describe.context.context (/truffle/packages/truffle/node_modules/mocha/lib/interfaces/bdd.js:44:27)
    at global.contract (/truffle/packages/truffle/build/webpack:/packages/truffle-core/lib/test.js:224:1)
    at Object.<anonymous> (/project/test/test_secret_ballot.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /truffle/packages/truffle/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/truffle/packages/truffle/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/truffle/packages/truffle/node_modules/mocha/lib/mocha.js:536:10)
    at /truffle/packages/truffle/build/webpack:/packages/truffle-core/lib/test.js:118:1
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Please provide the steps to reproduce.**
Follow steps in https://docs.oasiscloud.io/en/latest/secret-ballot/

**What is the expected behavior?**
Test should not crash out.

**Which blockchain are you running against? (local Parity blockchain, Oasis Devnet, Ganache, etc.)**
Oasis Devnet

**Please list the tools related to this issue including version numbers.**
Truffle v5.0.0 (core: 5.0.0)
Node v10.14.2

    "truffle-hdwallet-provider": "^1.0.0-web3one.0",
    "oasis-compile": "^1.0.1",
    "web3-provider-engine": "^14.1.0"
    "web3c": "^1.0.0"

**Comment by willscott** [comment]
There's an incompatibility in the recently released web3 v1.0 beta 38. we're working to push a new release to catch up to the breaking change. in the mean time, you can pin web3 to a working version with:
```
nom install web3@1.0.0-beta37
```

we're tracking this issue at https://github.com/oasislabs/web3c.js/issues/113

**Comment by aleph2012** [comment]
That works! By the way, it's web3@1.0.0-beta.37
